subsystems:
  drive:
    implemented: true
    talons:
      front_left_steer:  31
      front_right_steer: 34
      back_left_steer:   33
      back_right_steer:  32
    sparks:
      front_left_drive:  31 # 33
      front_right_drive: 34 # 32
      back_left_drive:   33
      back_right_drive:  32 # 30

    constants:
      steer_kp: 10
      steer_ki: 0
      steer_kd: 1

      # Used to lookup module offsets
      front_left_id:  1
      front_right_id: 4
      back_left_id:   3
      back_right_id:  2

  elevator:
    implemented: true
    falcons:
      liftLeader: 10
      liftFollower: 11
    solenoids:
      liftBrake: 0
    constants:
      intakeHeightOffset: 0

pcm: 0

constants:
  wheelbase_length: 30
  track_width: 30

  verbose: 1