# TODO Idea, add a Unit test that runs that verifies that no duplicate IPS have been added.
subsystems:
  drive:
    implemented: true
    talons:
      front_left_steer:  34
      front_right_steer: 32
      back_left_steer:   33
      back_right_steer:  31
    sparks:
      front_left_drive:  34
      front_right_drive: 32
      back_left_drive:   33
      back_right_drive:  31

    constants:
      steer_kp: 10
      steer_ki: 0
      steer_kd: 1

      # Used to lookup module offsets
      # TODO Idea use these values to look up the swerve module IDs
      front_left_id:  4 # 1
      front_right_id: 2 # 4
      back_left_id:   3 # 3
      back_right_id:  1 # 2

  elevator:
    implemented: true
    falcons:
      liftLeader: 10
      liftFollower: 11
    solenoids:
      liftBrake: 0 # Should be 0 - To test without the brake enabled, just set this to -1
    constants:
      intakeHeightOffset: 0

pneumaticsModule:
  id: 0
  type: CTREPCM # CTREPCM or REVPH

constants:
  wheelbase_length: 24
  track_width: 21.5

  verbose: 1